INSERT INTO tb_category (name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('MicroSD Cards', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Magnetic Field Therapy', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Ladders', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Ropes', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Bags & Sleeves', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Plant & Flower Protection', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Bottle Nipples', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Bath Sets & Kits', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Kitchen Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('V-rib Belts', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Height Charts', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Sand & Water Tables', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Processors', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Software Architecture', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Dhotis, Mundus & Lungis', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Mattresses & Box Springs', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Physics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Crime & Thriller', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Taped Diapers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Cosmetics & Jewellery', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Heating, Cooling & Air Quality', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Finnish', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Electric Can Openers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Shears & Scissors', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Lalique', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Swim Vests', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Organisers & Holders', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Swimwear', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Wireless Releases', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Baby Soaps', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Xbox One', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Camcorders', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Parsley', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Ceiling & In-Wall Speakers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Plastic Plants', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Theatre & Spectacles', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Makeup & Hair Dressing Heads', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Balls', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Inside Micrometers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Ophthalmology', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Internal ZIP Drives', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Econometrics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Racquets', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('USB Cables', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Rolls', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Water Purifier Accessories', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Pastelboard', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Safety Signs & Signals', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Stacking Chairs', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Kettles', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Radios & Boomboxes', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Apparel', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Archaeology', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Red Rice', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Juicer Mixer Grinders', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Ajwain', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Overalls', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Eyebrow Pencils', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Sling & Cross-Body Bags', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Humour', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Cymbal Sets', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Blasters & Toy Guns', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Triathlon Shoes', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Hand & Arm Protection', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Alternative Medicine', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('General Purpose Batteries & Battery Chargers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Cakes', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Air Purifiers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Pine Seeds', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Candy Floss Makers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Pumps & Filters', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Ponentine', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Toe Rings', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Toiletry Kits & Bags', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Business Card Holders', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Music Notebooks and Pads', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Templates', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('DJ Digital Media Players', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('External Hard Disks', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('LGBT Travel', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Motorcycle Speaker Systems', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Additive Manufacturing Products', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Booster Seats', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Hybrid Bikes', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Bubble Bath', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Mat Cutter Blades', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Garden Twine & Twist Ties', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Replacement Brush Heads', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Lens Hoods', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Steering Equipment', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Private', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Counting Frames', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Modems', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Tyre Care', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Shops & Accessories', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Oscilloscope Probes', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Drawing', NOW());
